var REGISTER_EVENT_TYPE = 'REGISTER_EVENT_TYPE';
var DOM_READ_TYPE = 'DOM_READ_TYPE';
var DOM_WRITE_TYPE = 'DOM_WRITE_TYPE';
var READ_INITIAL_STUFF = 'READ_INITIAL_STUFF';
var ON_CLICK = 'ON_CLICK';
var INIT_DONE = 'INIT_DONE';
var HELLO = 'HELLO';
